name: Déploiement sur GitHub Pages

on:
  push:
    branches:
      - main # Branche principale du dépôt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt principal
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: |
          # Installe les outils nécessaires pour construire le site
          # npm install ou toute autre commande requise
          echo "Installation des dépendances"

      - name: Construire le site
        run: |
          # Construis ton site (par exemple avec npm run build)
          echo "Construction du site"
          # npm run build

      - name: Déployer vers GitHub Pages
        run: |
          # Clone le dépôt mobifer.github.io
          git clone https://github.com/Mobifer/mobifer.github.io.git
          rsync -av --delete dist/ mobifer.github.io/

          # Pousser les modifications
          cd mobifer.github.io
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Déploiement automatique via GitHub Actions"
          git push
